// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tranduchungBTTH2.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    partial class ApplicationDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("tranduchungBTTH2.Models.sinhvien", b =>
                {
                    b.Property<int>("masinhvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("diachi")
                        .HasColumnType("TEXT");

                    b.Property<string>("tensinhvien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("masinhvien");

                    b.ToTable("sinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
